@echo off
cd /d "%~dp0backend"
set "BACKEND_PORT=18483"
set "BACKEND_HOST=0.0.0.0"
set "VIDEO_UNDERSTANDING_MAX_FRAMES=8"
set "BILIBILI_CDP_FIRST=1"
set "BILIBILI_LOWEST_VIDEO_FIRST=1"
set "BILIBILI_LOWEST_AUDIO_FIRST=1"
set "BILIBILI_MEDIA_RETRY_ATTEMPTS=8"
set "BILIBILI_SKIP_YTDLP_SUBTITLES=1"
set "NOTE_TASK_MAX_WORKERS=2"
"..\.venv\Scripts\python.exe" main.py
